### ISSUE TITLE
Could not find urlsrc in WOPI

### ISSUE THREAD

**Issue by ETararenko** [nextcloud/officeonline#18] opened 2020-09-30 06:36 UTC
**Describe the bug**
After trying to open the document, got the following error:
Could not find urlsrc in WOPI

**To Reproduce**
1. Go to install plugin for office online.
2. Entered the http url
3. After opening the the document, got the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/68062481/94650661-d053c900-02ff-11eb-9712-7a3545b8fc06.png)

**Client details:**
 - OS: Windows 10
 - Browser - chrome
 - Version 85.0.4183.121
 - Device:  desktop

## Server details

**Operating system**:
Ubuntu 18.04.3
**Web server:**
nginx
**Database:**
MySQL
**PHP version:**
7.2
**Nextcloud version:**
18.0.6
**Version of the officeonline app**
1.0
**Version of Office Online server**
2018

**Comment by degus2019** [comment] 2020-10-06 22:27
same here

Operating system:
FreeBSD 11.3-RELEASE-p14 amd64
Web server:
nginx
Database:
MySQL
PHP version:
 Version: 7.4.10 
Nextcloud version:
 19.0.3
Version of the officeonline app
1.0
Version of Office Online server
2019

**Comment by salagula** [comment] 2020-10-25 11:22
same on my side - config looks good and file creation is working (e.g. pptx) but cannot open the files

![image](https://user-images.githubusercontent.com/65948353/97105641-c2a22100-16bc-11eb-9e37-40f29f58b220.png)

**Comment by cwassen** [comment] 2020-10-25 16:00
I had this same issue and I found that my Office Online installation had to be HTTPS with a valid cert. If it was just HTTP and I set it up that way in Nextcloud, the settings it would say it could find the program, but still never worked with the same error you are showing. 

I am testing this on a VM nextcloud and using it in HTTP mode and was able to get things working.

**Comment by salagula** [comment] 2020-10-26 13:53
great - that fixed it!

**Comment by bi4lab** [comment] 2020-12-10 13:46
Hi, we have the same problem, the application setting should be just the https://nameserver or we is it possible to use http ?
On windows site, how should it have to be configured for minimal testing ?
We just installed it but it gives always Could not find urlsrc in WOPI

**Comment by shenvhua** [comment] 2021-01-18 19:36
we have https to office onlie，but same so

**Comment by salagula** [comment] 2021-01-19 07:36
maybe it helps - I have added a tutorial (just a pilot!) how I managed it
[OOS_NC.pdf](https://github.com/nextcloud/officeonline/files/5834314/OOS_NC.pdf)

**Comment by strawberryfly** [comment] 2021-03-22 07:36
hello, I have the same problem. I also have the whole thing running over https, certificate works without problems. The test page works but unfortunately the nextcloud shows me exactly the same error: Could not find urlsrc in WOPI

**Comment by andyxheli** [comment] 2022-04-18 17:55
@ETararenko is this still an issue? If not, can you please close this ticket ?

**Comment by snowtr** [comment] 2022-05-25 21:05
I'm also having this issue

**Comment by patschi** [comment] 2023-07-21 19:19
It looks like there're different possible root causes for a quite generic error message, but - based on above - seems to be related to overall configuration of Office Online Server (e.g. using HTTPs with trusted certificates). As everyone's environment is different and possible different causes, and seeing that most people were able to address the issues, I'll close this issue down to clean remaining issues up.

**Closed by patschi** 2023-07-21 19:19 UTC
