### ISSUE TITLE
DOCX and XLSX files download instead of opening on NC24

### ISSUE THREAD

**Issue by red-invader** [nextcloud/officeonline#309] opened 2022-06-15 10:40 UTC
When sharing a folder, DOCX and XLSX files are downloaded instead of opening in officeonline on the NC24.

When sharing a file - opens in officeonline without problems. In NC23 everything works without problems. the problem is observed only in version 24.

How can this be fixed?

NC 24.0.1
Ubuntu 20.04.4 LTS
PHP 8.0.20
mysql 10.8.3

**Comment by dasker** [comment] 2022-06-16 07:31
I confirm the issue.
When opening xlsx, docx files normally, the editor is launched:
/index.php/apps/files?dir=/share&openfile=739
When using a shared folder run:
/s/gDGiY659KDyTdo/download?path=%2F&files=123.docx

Mime types are registered, the problem is observed when using the File sharing module

**Comment by patschi** [comment] 2023-07-21 19:25
Closing this in favor of new issue #310 and being more complete information-wise (even if this one was raised a day before).

**Closed by patschi** 2023-07-21 19:25 UTC
