### ISSUE TITLE
Remove the black Bar on top to make better use of the Display

### ISSUE THREAD

**Issue by theoneandonly-vector** [nextcloud/officeonline#352] opened 2022-09-08 08:58 UTC
**Is your feature request related to a problem? Please describe.**
I would like to have the red marked space removed so I can use more of my Display to edit files

![image](https://user-images.githubusercontent.com/10380051/189080816-1ff20653-9ce0-45c4-b41a-c98d638b2c6d.png)

**Comment by thiblcr** [comment] 2022-10-18 11:55
Excellent idea, I was going to make the same suggestion.

**Comment by thiblcr** [comment] 2022-10-19 06:41
Here is a little trick to improve that:
https://github.com/nextcloud/officeonline/issues/313

It seems to be a Nextcloud24 related issue.

**Comment by ne0YT** [comment] 2022-10-19 08:42
this workaround works, but it should be fixed

**Comment by juliushaertl** [comment] 2022-10-19 17:13
Duplicate of #313, fix is in #370

**Closed by juliushaertl** 2022-10-19 17:13 UTC
