### ISSUE TITLE
Still annot open documents shared by link

### ISSUE THREAD

**Issue by MatheBoZz2804** [nextcloud/officeonline#554] opened 2024-04-25 19:23 UTC
**Describe the bug**
When sharing a MS Office file via link, it cannot be opened by using this link.

**To Reproduce**
1. Create a link to share the file
2. Edit the link, e. g. prevent downloading or editing (error happens with no matter what you configure)
3. Paste the link into a browser (no matter if on the network or from the internet)
4. The screen keeps blank. Office is not opened

**Expected behavior**
When opening the link in a web browser the MS Office file should open up.

**Screenshots**
![image](https://github.com/nextcloud/officeonline/assets/168129727/0a6f3409-8b2d-40a9-ae74-786aa68eb4ef)
![image](https://github.com/nextcloud/officeonline/assets/168129727/0dffeecf-1296-4ad1-a1b5-6c9a1986d74c)

**Client details:**
 - OS: Windows 10, iOS 17,...
 - Browser: Chrome, Safari, Firefox
 - Version most recent
 - Device: PC, iPhone

## Server details

**Operating system**: Debian 12.5 with latest patches

**Web server: Apache 2

**Database: MariaDB

**PHP version:** 8.1

**Nextcloud version:** 27.1.9

**Version of the officeonline app** 2.2.0, error occurs on all versions after 2.0.3, up to 2.0.3 everything is working fine!

**Version of Office Online server** most recent 2019 version

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by MatheBoZz2804** [comment] 2024-04-25 19:27
[nextcloud_last1000lines.log](https://github.com/nextcloud/officeonline/files/15119704/nextcloud_last1000lines.log)

**Comment by MatheBoZz2804** [comment] 2024-04-25 19:32
Also not working with version 28.0.5.

**Comment by MatheBoZz2804** [comment] 2024-04-28 19:52
Tried updating PHP to version 8.2: Still not working with version 2.2.0; version 2.0.3 works fine however

**Comment by johnakerlund** [comment] 2024-04-29 09:26
> Also not working with version 28.0.5.

issue also persists in version 29.0.0

**Comment by schukevich** [comment] 2024-05-02 13:19
Can confirm, have same problem with 28.0.4, 28.0.5, 29.0.0

Opening document from folder works as expected
Editing/viewing from shared link is not working

Nextcloud log (all versions above):

```
QueryNotFoundException
Could not resolve OCA\Officeonline\Listener\SharingLoadAdditionalScriptsListener! Class "OCA\Officeonline\Listener\SharingLoadAdditionalScriptsListener" does not exist
Could not load event listener service OCA\Officeonline\Listener\SharingLoadAdditionalScriptsListener: Could not resolve OCA\Officeonline\Listener\SharingLoadAdditionalScriptsListener! Class "OCA\Officeonline\Listener\SharingLoadAdditionalScriptsListener" does not exist. Make sure the class is auto-loadable by the Nextcloud server container
```

**Comment by johnakerlund** [comment] 2024-05-07 09:56
@juliushaertl any update on this? the patch posted in #521 has not resolved this issue, it has been a problem every version after 2.0.3

**Comment by Orchal** [comment] 2024-05-10 07:56
Hi, the file lib/Listener/SharingLoadAdditionalScriptsListener.php does not exists.

**Comment by schukevich** [comment] 2024-05-10 08:14
@Orchal @johnakerlund @MatheBoZz2804 
Installing patch maunally worked for me, but broke my nextcloud color scheme somehow
I have NC installed with apache and php-fpm without docker, Oracle Linux 8, i went to my `../nextcloud/apps/officeonline` folder and executed these commands

```
wget -O /tmp/officeonline-553.patch https://github.com/nextcloud/officeonline/pull/553.patch
patch -p1 < /tmp/officeonline-553.patch
```
then
`systemctl restart httpd php-fpm` and reset my browser cache
After that documents sharing working correctly.

**Comment by johnakerlund** [comment] 2024-05-11 10:55
@schukevich i will give it another try on one of my nc-instances, what version of nextcloud and officeonline are u running?

**Comment by MatheBoZz2804** [comment] 2024-05-11 18:59
Updated to the most recent version of Office Online Integration and applied the patch. Also updated Nextcloud to version 28.0.5. Shared links can be opened again. However, when opening the link on a mobile device (no matter if Android or iPhone) you need to require the Desktop view. With the regular mobile view I receive a Not found error.
![426d6dff-ac45-4987-9ecc-e175c224a3de](https://github.com/nextcloud/officeonline/assets/168129727/34d2b0e9-ccd9-417c-851f-5ba2bc57f3bb)

**Comment by elzody** [comment] 2024-06-07 16:07
Working on a release which should fix the problem so patching won't be required anymore

**Comment by schukevich** [comment] 2024-06-07 17:53
> Released v2.2.1 which includes the missing file, so should not have to apply the patch anymore to get it working. can someone confirm it works as expected now?

Updated plugin to 2.2.1 on my instance
Not available from nextcloud app gallery right now, installed manually
Working as expected👍

**Comment by MatheBoZz2804** [comment] 2024-06-08 11:29
Hi, I‘ve just installed the new version. It still requires the desktop view.

**Comment by elzody** [comment] 2024-06-10 14:39
@MatheBoZz2804 Hey there. Unfortunately I don't really have a way to try reproducing the mobile issue, but I will try my best to look into it sometime soon. Overall, since the Office online integration update to 2.2.1, is it working again though?

**Comment by MatheBoZz2804** [comment] 2024-06-10 15:36
Hi there,

The Office Online integration also works with shared links now, but I haven‘t tried reinstalling the App without the yet.

Kind regards

Am 10.06.2024 um 16:40 schrieb Elizabeth Danzberger ***@***.***>:

﻿

@MatheBoZz2804<https://github.com/MatheBoZz2804> Hey there. Unfortunately I don't really have a way to try reproducing the mobile issue, but I will try my best to look into it sometime soon. Overall, since the Office online integration update to 2.2.1, is it working again though?

**Comment by juliushaertl** [comment] 2024-06-13 13:31
Mobile also seems out of scope of this issue, please check for other existing issues or file a new one if that is not tracked anywhere yet.

**Closed by juliushaertl** 2024-06-13 13:31 UTC
