### ISSUE TITLE
PDF are opening under ms office

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/officeonline#234] opened 2021-12-03 02:14 UTC
**Describe the bug**

**To Reproduce**
1. Open PDF file 

**Expected behavior**
Should open with pdf viewer

**Screenshots**
![image](https://user-images.githubusercontent.com/59488153/144533176-41fca217-d3dc-48f9-98ca-d7e625902830.jpeg)
## Server details

**Operating system**:
**Web server:**
Ubuntu 20.04
**Database:**
MariaDb 
**PHP version:**
8.0
**Nextcloud version:**
23.0.0
**Version of the officeonline app**
1.1.1
**Version of Office Online server**
2019

**Comment by andyxheli** [comment] 2021-12-08 16:26
@juliushaertl Quick question i know youre busy just wanted to see if you have anything on top of your head where in the code i can change so pdfs done open with OfficeOnline and open with the default pdf viewer. Id be more then happy to do the work just need a little help where to look and what files to change.

**Comment by koelle25** [comment] 2021-12-13 13:15
Hi @andyxheli
This issue was already open under #86 but got closed by the author - although it really is NOT fixed at all. See [my comment](https://github.com/nextcloud/officeonline/issues/86#issuecomment-919380751) and [hheinen's comment](https://github.com/nextcloud/officeonline/issues/86#issuecomment-797521807) for a workaround.

But imo there should be a configuration option in the settings screen. Currently it looks like this for me:
![OfficeOnline App settings screen](https://user-images.githubusercontent.com/915514/145819018-9b07a07a-fd67-4eea-b5ba-02a849137c31.png)

**Comment by andyxheli** [comment] 2021-12-13 13:37
Close per above comments.

**Comment by koelle25** [comment] 2021-12-13 13:45
Hey @andyxheli please do not close this issue! It should stay open until it gets properly fixed. The above is merely a workaround.

**Comment by andyxheli** [comment] 2021-12-13 13:46
Oaky no problem reopening it

**Comment by juliushaertl** [comment] 2021-12-15 07:45
So the problem is actually that with the viewer app there is currently no way to register mimetypes that are NOT the default opener. The path to resolve this would be to avoid that the optional mimetype list is not added to the viewer then:

https://github.com/nextcloud/officeonline/blob/master/src/viewer.js#L3

Source of that list is https://github.com/nextcloud/officeonline/blob/master/lib/Capabilities.php#L66-L68

**Closed** 2022-01-04 10:26 UTC
Labels: 1. to develop, bug
